export const AUTH_ACTION_TYPES = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};
export const PROJECT_ACTION_TYPES = {
  UPDATE_PROJECT_SUCCESS: "UPDATE_PROJECT_SUCCESS",
};
